version: '3.8'

services:
  app:
    build:
      target: php-fpm-prod   # Build only the php-fpm stage from Dockerfile
      context: .
    # volumes:
    #   - .:/var/www/html
    expose:
      - "9000"               # Expose port 9000 internally, no need to publish to host
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_test
      DB_USERNAME: root
      DB_PASSWORD: secret

  nginx:
    build:
      target: production     # Build the nginx stage from Dockerfile
      context: .
    ports:
      - "80:80"              # Expose Nginx on host port 80
    volumes:
      - .:/var/www/html      # Share app code with nginx container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Your nginx config
    depends_on:
      - app

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_test
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql.conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql.conf/mysql.conf.d:/etc/mysql/mysql.conf.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
